"""Report generation route"""
import io
from datetime import datetime
from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import StreamingResponse
from sqlalchemy.orm import Session
import json

from app.database import get_db
from app.models.evidence import Evidence, CustodyEvent
from app.models.case import Case
from app.models.ai_analysis import AIAnalysis
from app.models.user import User
from app.security.auth import require_permission
from app.blockchain import verify_evidence_blocks
from app.utils.helpers import create_audit_log

router = APIRouter(prefix="/api/reports", tags=["Reports"])


@router.get("/evidence/{evidence_id}")
def generate_evidence_report(
    evidence_id: int,
    user: User = Depends(require_permission("reports.generate")),
    db: Session = Depends(get_db),
):
    ev = db.query(Evidence).filter(Evidence.id == evidence_id).first()
    if not ev:
        raise HTTPException(status_code=404, detail="Evidence not found")

    case = db.query(Case).filter(Case.id == ev.case_id).first()
    ai = db.query(AIAnalysis).filter(AIAnalysis.evidence_id == ev.id).first()
    custody = db.query(CustodyEvent).filter(CustodyEvent.evidence_id == ev.id).order_by(CustodyEvent.timestamp).all()
    bc_result = verify_evidence_blocks(db, ev.evidence_id)

    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.units import inch, cm
        from reportlab.lib.colors import HexColor
        from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle

        buffer = io.BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=A4, topMargin=1.5*cm, bottomMargin=1.5*cm)
        styles = getSampleStyleSheet()

        title_style = ParagraphStyle('Title2', parent=styles['Title'], fontSize=18,
                                      textColor=HexColor('#1a1a2e'))
        heading_style = ParagraphStyle('Heading', parent=styles['Heading2'], fontSize=14,
                                       textColor=HexColor('#16213e'), spaceAfter=10)
        normal_style = styles['Normal']

        elements = []

        # Title
        elements.append(Paragraph("EVIDENCE VAULT — Evidence Report", title_style))
        elements.append(Spacer(1, 0.3*inch))
        elements.append(Paragraph(f"Generated: {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}", normal_style))
        elements.append(Paragraph(f"Generated by: {user.full_name} ({user.role})", normal_style))
        elements.append(Spacer(1, 0.3*inch))

        # Evidence Passport
        elements.append(Paragraph("Evidence Passport", heading_style))
        passport_data = [
            ["Evidence ID", ev.evidence_id],
            ["Case", f"{case.case_number} — {case.title}" if case else "N/A"],
            ["Original Filename", ev.original_filename],
            ["Type", ev.evidence_type],
            ["MIME Type", ev.mime_type],
            ["File Size", f"{ev.file_size:,} bytes"],
            ["SHA-256 Hash", ev.sha256_hash],
            ["Classification", ev.classification],
            ["Current Version", str(ev.current_version)],
            ["Current Custodian", ev.current_custodian],
            ["Integrity Status", ev.integrity_status],
            ["Blockchain Status", ev.blockchain_status],
            ["Created", ev.created_at.strftime('%Y-%m-%d %H:%M') if ev.created_at else "N/A"],
        ]
        t = Table(passport_data, colWidths=[3.5*cm, 13*cm])
        t.setStyle(TableStyle([
            ('FONTSIZE', (0, 0), (-1, -1), 9),
            ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
            ('GRID', (0, 0), (-1, -1), 0.5, HexColor('#cccccc')),
            ('VALIGN', (0, 0), (-1, -1), 'TOP'),
            ('TOPPADDING', (0, 0), (-1, -1), 4),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
        ]))
        elements.append(t)
        elements.append(Spacer(1, 0.3*inch))

        # AI Analysis
        if ai:
            elements.append(Paragraph("AI Analysis", heading_style))
            ai_data = [
                ["Document Type", ai.document_type],
                ["AI Confidence", f"{ai.confidence:.0%}"],
                ["Risk Score", f"{ai.risk_score:.0f}/100"],
                ["Risk Level", ai.risk_level],
                ["Key Persons", str(ai.key_persons_count)],
                ["Locations", str(ai.locations_count)],
                ["Dates Detected", str(ai.dates_count)],
            ]
            t2 = Table(ai_data, colWidths=[3.5*cm, 13*cm])
            t2.setStyle(TableStyle([
                ('FONTSIZE', (0, 0), (-1, -1), 9),
                ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
                ('GRID', (0, 0), (-1, -1), 0.5, HexColor('#cccccc')),
                ('TOPPADDING', (0, 0), (-1, -1), 4),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
            ]))
            elements.append(t2)
            if ai.summary:
                elements.append(Spacer(1, 0.15*inch))
                elements.append(Paragraph(f"<b>Summary:</b> {ai.summary}", normal_style))
            elements.append(Spacer(1, 0.3*inch))

        # Chain of Custody
        if custody:
            elements.append(Paragraph("Chain of Custody", heading_style))
            cust_data = [["Timestamp", "Actor", "Role", "Action", "Condition"]]
            for c in custody:
                cust_data.append([
                    c.timestamp.strftime('%Y-%m-%d %H:%M') if c.timestamp else "",
                    c.actor_name,
                    c.actor_role,
                    c.action,
                    c.evidence_condition,
                ])
            t3 = Table(cust_data, colWidths=[3*cm, 3.5*cm, 3*cm, 4*cm, 3*cm])
            t3.setStyle(TableStyle([
                ('FONTSIZE', (0, 0), (-1, -1), 8),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('BACKGROUND', (0, 0), (-1, 0), HexColor('#1a1a2e')),
                ('TEXTCOLOR', (0, 0), (-1, 0), HexColor('#ffffff')),
                ('GRID', (0, 0), (-1, -1), 0.5, HexColor('#cccccc')),
                ('TOPPADDING', (0, 0), (-1, -1), 3),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 3),
            ]))
            elements.append(t3)
            elements.append(Spacer(1, 0.3*inch))

        # Blockchain Verification
        elements.append(Paragraph("Blockchain Verification", heading_style))
        bc_status = "VERIFIED ✓" if bc_result.get("valid") else "INTEGRITY ISSUE ✕"
        elements.append(Paragraph(f"<b>Status:</b> {bc_status}", normal_style))
        elements.append(Paragraph(f"<b>Blocks:</b> {len(bc_result.get('blocks', []))}", normal_style))
        if bc_result.get("errors"):
            for err in bc_result["errors"]:
                elements.append(Paragraph(f"⚠ Block #{err['block_index']}: {err['error']}", normal_style))

        # Footer
        elements.append(Spacer(1, 0.5*inch))
        elements.append(Paragraph("— End of Report —", ParagraphStyle('Center', parent=normal_style, alignment=1)))
        elements.append(Paragraph("This report was generated by EvidenceVault Secure Document Management System.",
                                  ParagraphStyle('Footer', parent=normal_style, fontSize=7, alignment=1)))

        doc.build(elements)
        buffer.seek(0)

        create_audit_log(db, user_id=user.id, user_email=user.email, role=user.role,
                        action="REPORT_GENERATED", resource_type="EVIDENCE",
                        resource_id=ev.evidence_id)

        return StreamingResponse(
            buffer,
            media_type="application/pdf",
            headers={"Content-Disposition": f"attachment; filename=\"report_{ev.evidence_id}.pdf\""},
        )

    except ImportError:
        # Fallback: return JSON report if reportlab not available
        report = {
            "evidence_id": ev.evidence_id,
            "case_number": case.case_number if case else "",
            "filename": ev.original_filename,
            "sha256_hash": ev.sha256_hash,
            "classification": ev.classification,
            "integrity_status": ev.integrity_status,
            "blockchain_result": bc_result,
            "custody_chain": [{"actor": c.actor_name, "action": c.action,
                              "timestamp": c.timestamp.isoformat() if c.timestamp else ""} for c in custody],
            "generated_at": datetime.utcnow().isoformat(),
        }
        return report
